# Generated by Django 6.0.2 on 2026-02-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
    ]
