# Generated by Django 6.0.2 on 2026-02-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signings", "0002_remove_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grub",
            name="price_nonveg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="grub",
            name="price_veg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
