# Generated by Django 6.0.2 on 2026-02-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signings", "0003_alter_grub_price_nonveg_alter_grub_price_veg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grub",
            name="price_nonveg",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="grub",
            name="price_veg",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
